[profile.default]
src = 'contracts'
out = 'gen/out'
libs = ['node_modules', 'lib']
cache_path  = 'gen/cache_forge'
broadcast = 'gen/broadcast'

solc_version='0.8.22'
evm_version='paris'
optimizer = true
optimizer_runs = 9999

remappings = [
    "tapioca-strategies/=contracts/",
	"tapioca-sdk/=gitmodule/tapioca-sdk/contracts/",
    "yieldbox/=lib/tap-yieldbox/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]


[etherscan]
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api"}
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api"}

[profile.default.invariant]
fail_on_revert = false
runs = 100
depth = 10