name: run-test

on:
  pull_request:
    branches: [ "*" ]

env:
  FOUNDRY_PROFILE: ci
  RPC_URL: ${{ vars.RPC_URL }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly

#      - name: Install Forge Dependencies
#        run: |
#          forge install foundry-rs/forge-std --no-commit
#          forge install Tapioca-DAO/tap-yieldbox/tree/fix-dependencies --no-commit
#          forge install Tapioca-DAO/tap-utils --no-commit
#          forge install Tapioca-DAO/tapioca-sdk --no-commit
#          forge install openzeppelin/openzeppelin-contracts@v4.9.3 --no-commit
#        id: install

      - name: Install Yarn Dependencies
        run: |
          yarn install
        id: yarn-install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test --mc yvTokenStrategy -vvv
        id: test
