name: run-test

on:
  pull_request:
    branches: [ "*" ]

env:
  FOUNDRY_PROFILE: ci
  RPC_URL: ${{ vars.RPC_URL }}

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly

      - name: Install Forge Dependencies
        run: |
          forge install
        id: install

      - name: Install Yarn Dependencies
        run: |
          yarn install
        id: yarn-install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test --mc yvTokenStrategy -vvv
        id: test
